export enum PROVIDERS {
  MODULE_OPTIONS = "MODULE_OPTIONS_PROVIDER",
  PRISMA_SERVICE = "PRISMA_SERVICE_PROVIDER",
  ABILITY_CHECKER_BUILDER = "ABILITY_CHECKER_BUILDER_PROVIDER",
}

export const ABILITY_METADATA = "AUTHO_ABIILTY_METADATA"